### ISSUE TITLE
`wp bgc update` results in PHP Fatal error:  Uncaught Error: Call to a member function get_data() on null

### ISSUE THREAD

**Issue by zamoose** [jmichaelward/board-game-collector#22]
Latest pull from `develop` results in an error when attempting to update the collection. 

```PHP Fatal error:  Uncaught Error: Call to a member function get_data() on null in [...]src/Updater/GamesUpdater.php:51```

Full-ish stack trace here:

```
Fatal error: Uncaught Error: Call to a member function get_data() on null in [...]/src/Updater/GamesUpdater.php:51
Stack trace:
#0 [...]/src/Updater/GamesUpdater.php(71): JMichaelWard\BoardGameCollector\Updater\GamesUpdater->hydrate()
#1 [...]/src/UI/Cli/Command/BgcCommand.php(61): JMichaelWard\BoardGameCollector\Updater\GamesUpdater->update_collection()
#2 [internal function]: JMichaelWard\BoardGameCollector\UI\Cli\Command\BgcCommand->update(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.ph in [...]/src/Updater/GamesUpdater.php on line 51
```

**Comment by jmichaelward** [comment]
Thanks for reporting this, @zamoose. I've been treating `develop` as a dirty branch and doing direct development in it, and I realized I left it in a completely unstable state since I last picked up the project. The current version of the develop branch should be stable enough for you to no longer receive this error.

Going forward, I'm going to start working in feature branches and merging into develop once those features are stable enough to testing. I have a bit more free time these days, so I'm working through a set of ideas to determine what features, enhancements, and improvements I need to make to the plugin to give it some more utility as I push toward an initial release.

Let me know if you're continuing to see this issue in the develop branch, and if not, let's close this out.

**Comment by zamoose** [comment]
Yup! No longer occurring.
