### ISSUE TITLE
Fatal error when trying to activate plugin

### ISSUE THREAD

**Issue by filipvorkapic** [jmichaelward/board-game-collector#54]
Hi,

I'm trying to use your plugin on my WP site, pa when I try to activate it an fatal error occurs:

![image](https://user-images.githubusercontent.com/15672918/163196280-48be85a2-7528-4d31-9386-96acacda1c79.png)

Any ideas what could be causing this and/or how to remedy it.

Thanks in advance!

**Comment by jmichaelward** [comment]
Hi @filipvorkapic,

Thanks for trying out this plugin! Please note that I'm not actively developing this project - it's something I tinker with from time to time to try out new ideas, and I haven't really given it much attention in the past couple years as I've been more interested in exploring other languages and frameworks in my spare time.

My latest commits were tinkering with the idea of shipping an included `composer.phar` file with the repository which would check for the presence of the main plugin class on activation, and would bail if the class was present. Otherwise, the plugin would attempt to install the `vendor` directory with the class definitions right to the plugin. The logic in there was incorrect, which is why you were seeing the fatal error. I've patched this, so it should hopefully work for you, but please note that A) I may change this in the future, and B) this plugin is not at a full versioned release yet so I wouldn't install it in any production environments.

If you continue to work with this and encounter any other issues, I'd be happy to look into them if you open an issue here in the repo. Thanks again for checking out my work!

Best,

Jeremy
